from app.schemas.fleet import Fleet, Ship, Position


def get_initial_fleet() -> Fleet:
    return Fleet(
        ships=[
            Ship(
                id="FS-101",
                name="Indus Voyager",
                position=Position(lat=26.55, lng=56.2),
                speed_knots=15,
                heading=118,
                destination="MCT-1",
                fuel_tons=6900,
                cargo="refined fuel",
            ),
            Ship(
                id="FS-102",
                name="Ravi Trader",
                position=Position(lat=25.5, lng=57.2),
                speed_knots=17,
                heading=268,
                destination="DXB-1",
                fuel_tons=5750,
                cargo="containers",
            ),
            Ship(
                id="FS-103",
                name="Chenab Star",
                position=Position(lat=25.7, lng=53.0),
                speed_knots=14,
                heading=92,
                destination="MCT-1",
                fuel_tons=7350,
                cargo="LNG",
            ),
            Ship(
                id="FS-104",
                name="Sapphire Dawn",
                position=Position(lat=26.4, lng=56.0),
                speed_knots=12,
                heading=124,
                destination="SOH-1",
                fuel_tons=6100,
                cargo="grain",
            ),
            Ship(
                id="FS-105",
                name="Karachi Horizon",
                position=Position(lat=27.5, lng=51.2),
                speed_knots=13,
                heading=172,
                destination="DOH-1",
                fuel_tons=7900,
                cargo="crude oil",
            ),
            Ship(
                id="FS-106",
                name="Makran Runner",
                position=Position(lat=25.4, lng=54.53),
                speed_knots=20,
                heading=286,
                destination="DOH-1",
                fuel_tons=4550,
                cargo="containers",
            ),
            Ship(
                id="FS-107",
                name="Gwadar Pioneer",
                position=Position(lat=26.5, lng=53.5),
                speed_knots=13,
                heading=276,
                destination="KWT-1",
                fuel_tons=3250,
                cargo="crude oil",
            ),
            Ship(
                id="FS-108",
                name="Blue Crescent",
                position=Position(lat=24.93, lng=56.94),
                speed_knots=18,
                heading=244,
                destination="DMM-1",
                fuel_tons=5600,
                cargo="automobiles",
            ),
            Ship(
                id="FS-109",
                name="Sindh Mariner",
                position=Position(lat=28.2, lng=50.3),
                speed_knots=12,
                heading=181,
                destination="BAH-1",
                fuel_tons=8050,
                cargo="crude oil",
            ),
            Ship(
                id="FS-110",
                name="Coastal Arrow",
                position=Position(lat=25.02, lng=57.96),
                speed_knots=19,
                heading=292,
                destination="BND-1",
                fuel_tons=6450,
                cargo="containers",
            ),
            Ship(
                id="FS-111",
                name="Indigo Pearl",
                position=Position(lat=25.64, lng=52.18),
                speed_knots=17,
                heading=101,
                destination="MCT-1",
                fuel_tons=7700,
                cargo="LNG",
            ),
            Ship(
                id="FS-112",
                name="Arabian Crest",
                position=Position(lat=29.1, lng=48.8),
                speed_knots=11,
                heading=151,
                destination="SOH-1",
                fuel_tons=8700,
                cargo="cement",
            ),
            Ship(
                id="FS-113",
                name="Sea Falcon",
                position=Position(lat=24.6, lng=57.3),
                speed_knots=20,
                heading=328,
                destination="BAH-1",
                fuel_tons=6150,
                cargo="containers",
            ),
            Ship(
                id="FS-114",
                name="Pearl Navigator",
                position=Position(lat=24.12, lng=58.43),
                speed_knots=12,
                heading=301,
                destination="DOH-1",
                fuel_tons=5000,
                cargo="bulk grain",
            ),
            Ship(
                id="FS-115",
                name="Horizon Atlas",
                position=Position(lat=26.34, lng=55.91),
                speed_knots=14,
                heading=224,
                destination="MCT-1",
                fuel_tons=7250,
                cargo="crude oil",
            ),
        ]
    )
